apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    access: proxy
    url: db:5432
    database: hydro_dev
    user: hydro
    secureJsonData:
      password: hydro
    jsonData:
      sslmode: disable
      timescaledb: true
    editable: true

