<?php

namespace Database\Seeders;

use App\Models\Plant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class PlantTaxonomySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $taxonomyPath = base_path('config/plant_taxonomies.json');
        $taxonomies = [];

        if (File::exists($taxonomyPath)) {
            $taxonomies = json_decode(File::get($taxonomyPath), true) ?? [];
        }

        $substrateDefault = Arr::get($taxonomies, 'substrate_type.0.id', 'coco');
        $systemDefault = Arr::get($taxonomies, 'growing_system.0.id', 'nft');
        $photoperiodDefault = Arr::get($taxonomies, 'photoperiod_preset.1.id', '16_8');

        $plants = [
            [
                'slug' => 'basil-genovese',
                'name' => 'Базилик (Генуэзский)',
                'species' => 'Ocimum basilicum',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 20, 'max' => 27],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 1.6],
                ],
                'growth_phases' => [
                    ['name' => 'Рассада', 'duration_days' => 14],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор урожая', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'tomato',
                'name' => 'Томат',
                'species' => 'Solanum lycopersicum',
                'substrate_type' => 'rockwool',
                'growing_system' => 'drip',
                'photoperiod_preset' => '18_6',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 18, 'max' => 26],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.8, 'max' => 6.5],
                    'ec' => ['min' => 2.0, 'max' => 3.5],
                    'co2' => ['min' => 700, 'max' => 1000],
                    'dli' => ['min' => 20, 'max' => 30],
                ],
                'growth_phases' => [
                    ['name' => 'Рассада', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 42],
                ],
            ],
            [
                'slug' => 'cucumber',
                'name' => 'Огурец',
                'species' => 'Cucumis sativus',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '18_6',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 20, 'max' => 28],
                    'humidity' => ['min' => 70, 'max' => 85],
                    'ph' => ['min' => 5.6, 'max' => 6.2],
                    'ec' => ['min' => 1.8, 'max' => 2.8],
                    'co2' => ['min' => 700, 'max' => 1000],
                    'dli' => ['min' => 18, 'max' => 25],
                ],
                'growth_phases' => [
                    ['name' => 'Рассада', 'duration_days' => 14],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Цветение', 'duration_days' => 14],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
            [
                'slug' => 'strawberry',
                'name' => 'Клубника',
                'species' => 'Fragaria × ananassa',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.2],
                    'ec' => ['min' => 1.2, 'max' => 1.8],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 14],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
            [
                'slug' => 'blueberry',
                'name' => 'Голубика',
                'species' => 'Vaccinium corymbosum',
                'substrate_type' => 'peat',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 60, 'max' => 80],
                    'ph' => ['min' => 4.5, 'max' => 5.5],
                    'ec' => ['min' => 1.0, 'max' => 1.6],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 12, 'max' => 20],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 42],
                ],
            ],
            [
                'slug' => 'raspberry',
                'name' => 'Малина',
                'species' => 'Rubus idaeus',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 18, 'max' => 26],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.4, 'max' => 2.2],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 14, 'max' => 20],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
            [
                'slug' => 'blackberry',
                'name' => 'Ежевика',
                'species' => 'Rubus fruticosus',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 18, 'max' => 26],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.4, 'max' => 2.2],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 14, 'max' => 20],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
            [
                'slug' => 'pepper-sweet',
                'name' => 'Перец сладкий',
                'species' => 'Capsicum annuum',
                'substrate_type' => 'rockwool',
                'growing_system' => 'drip',
                'photoperiod_preset' => '18_6',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 20, 'max' => 28],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.8, 'max' => 6.5],
                    'ec' => ['min' => 2.0, 'max' => 3.0],
                    'co2' => ['min' => 700, 'max' => 1000],
                    'dli' => ['min' => 18, 'max' => 25],
                ],
                'growth_phases' => [
                    ['name' => 'Рассада', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 42],
                ],
            ],
            [
                'slug' => 'eggplant',
                'name' => 'Баклажан',
                'species' => 'Solanum melongena',
                'substrate_type' => 'rockwool',
                'growing_system' => 'drip',
                'photoperiod_preset' => '18_6',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 22, 'max' => 28],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.8, 'max' => 6.5],
                    'ec' => ['min' => 2.5, 'max' => 3.5],
                    'co2' => ['min' => 700, 'max' => 1000],
                    'dli' => ['min' => 18, 'max' => 25],
                ],
                'growth_phases' => [
                    ['name' => 'Рассада', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 42],
                ],
            ],
            [
                'slug' => 'peas',
                'name' => 'Горох',
                'species' => 'Pisum sativum',
                'substrate_type' => $substrateDefault,
                'growing_system' => 'ebb_flow',
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 22],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.8, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 2.0],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 7],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Цветение', 'duration_days' => 14],
                    ['name' => 'Плодоношение', 'duration_days' => 21],
                ],
            ],
            [
                'slug' => 'lettuce',
                'name' => 'Салат листовой',
                'species' => 'Lactuca sativa',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 22],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.2],
                    'ec' => ['min' => 0.8, 'max' => 1.6],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 17],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 3],
                    ['name' => 'Рассада', 'duration_days' => 10],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'lettuce-iceberg',
                'name' => 'Салат Айсберг',
                'species' => 'Lactuca sativa',
                'variety' => 'Iceberg',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 14, 'max' => 20],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.6, 'max' => 6.2],
                    'ec' => ['min' => 1.2, 'max' => 1.8],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 17],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 3],
                    ['name' => 'Рассада', 'duration_days' => 10],
                    ['name' => 'Формирование кочана', 'duration_days' => 28],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'arugula',
                'name' => 'Руккола',
                'species' => 'Eruca sativa',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 22],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.0, 'max' => 1.6],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 17],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 3],
                    ['name' => 'Вегетация', 'duration_days' => 18],
                    ['name' => 'Сбор', 'duration_days' => 5],
                ],
            ],
            [
                'slug' => 'chinese-cabbage',
                'name' => 'Пекинская капуста',
                'species' => 'Brassica rapa subsp. pekinensis',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 22],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.5, 'max' => 2.5],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 4],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Формирование кочана', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'spinach',
                'name' => 'Шпинат',
                'species' => 'Spinacia oleracea',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 12, 'max' => 20],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.8, 'max' => 6.5],
                    'ec' => ['min' => 1.8, 'max' => 2.3],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 5],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'kale',
                'name' => 'Кейл',
                'species' => 'Brassica oleracea var. sabellica',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 14, 'max' => 22],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.8, 'max' => 2.4],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 4],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'chard',
                'name' => 'Мангольд',
                'species' => 'Beta vulgaris subsp. vulgaris',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.8, 'max' => 2.3],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 5],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'dill',
                'name' => 'Укроп',
                'species' => 'Anethum graveolens',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 1.8],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 5],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'parsley',
                'name' => 'Петрушка',
                'species' => 'Petroselinum crispum',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.4, 'max' => 2.0],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 7],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'cilantro',
                'name' => 'Кинза',
                'species' => 'Coriandrum sativum',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 22],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 1.8],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Проращивание', 'duration_days' => 7],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'mint',
                'name' => 'Мята',
                'species' => 'Mentha spicata',
                'substrate_type' => $substrateDefault,
                'growing_system' => $systemDefault,
                'photoperiod_preset' => $photoperiodDefault,
                'seasonality' => 'all_year',
                'environment_requirements' => [
                    'temperature' => ['min' => 18, 'max' => 26],
                    'humidity' => ['min' => 55, 'max' => 70],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.4, 'max' => 2.0],
                    'co2' => ['min' => 500, 'max' => 800],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 10],
                    ['name' => 'Вегетация', 'duration_days' => 21],
                    ['name' => 'Сбор', 'duration_days' => 7],
                ],
            ],
            [
                'slug' => 'currant-black',
                'name' => 'Смородина черная',
                'species' => 'Ribes nigrum',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 2.0],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
            [
                'slug' => 'gooseberry',
                'name' => 'Крыжовник',
                'species' => 'Ribes uva-crispa',
                'substrate_type' => 'coco',
                'growing_system' => 'drip',
                'photoperiod_preset' => '16_8',
                'seasonality' => 'multi_cycle',
                'environment_requirements' => [
                    'temperature' => ['min' => 16, 'max' => 24],
                    'humidity' => ['min' => 60, 'max' => 75],
                    'ph' => ['min' => 5.5, 'max' => 6.5],
                    'ec' => ['min' => 1.2, 'max' => 2.0],
                    'co2' => ['min' => 600, 'max' => 900],
                    'dli' => ['min' => 12, 'max' => 18],
                ],
                'growth_phases' => [
                    ['name' => 'Укоренение', 'duration_days' => 21],
                    ['name' => 'Вегетация', 'duration_days' => 28],
                    ['name' => 'Цветение', 'duration_days' => 21],
                    ['name' => 'Плодоношение', 'duration_days' => 35],
                ],
            ],
        ];

        foreach ($plants as $plant) {
            $slug = $plant['slug'] ?? Str::slug($plant['name'].'-'.($plant['variety'] ?? ''));
            $model = Plant::updateOrCreate(
                ['slug' => $slug],
                $plant
            );

            $model->priceVersions()->firstOrCreate(
                ['effective_from' => now()->startOfMonth()],
                [
                    'currency' => 'RUB',
                    'seedling_cost' => 15.0,
                    'substrate_cost' => 8.5,
                    'nutrient_cost' => 4.2,
                    'labor_cost' => 6.0,
                    'wholesale_price' => 55.0,
                    'retail_price' => 85.0,
                    'source' => 'seed',
                ]
            );
        }
    }
}
