/**
 * @file storage_irrigation_node_config.h
 * @brief Единый source of truth для конфигурации storage_irrigation_node.
 */

#ifndef STORAGE_IRRIGATION_NODE_CONFIG_H
#define STORAGE_IRRIGATION_NODE_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "driver/gpio.h"
#include "cJSON.h"

#define STORAGE_IRRIGATION_NODE_DEFAULT_NODE_ID "nd-irrig-1"
#define STORAGE_IRRIGATION_NODE_DEFAULT_GH_UID "gh-1"
#define STORAGE_IRRIGATION_NODE_DEFAULT_ZONE_UID "zn-3"

#define STORAGE_IRRIGATION_NODE_DEFAULT_MQTT_HOST "192.168.1.10"
#define STORAGE_IRRIGATION_NODE_DEFAULT_MQTT_PORT 1883
#define STORAGE_IRRIGATION_NODE_DEFAULT_MQTT_KEEPALIVE 30

#define STORAGE_IRRIGATION_NODE_I2C_BUS_0_SDA 21
#define STORAGE_IRRIGATION_NODE_I2C_BUS_0_SCL 22
#define STORAGE_IRRIGATION_NODE_I2C_CLOCK_SPEED 100000

#define STORAGE_IRRIGATION_NODE_PUMP_MAIN_GPIO 25
#define STORAGE_IRRIGATION_NODE_VALVE_CLEAN_FILL_GPIO 26
#define STORAGE_IRRIGATION_NODE_VALVE_CLEAN_SUPPLY_GPIO 27
#define STORAGE_IRRIGATION_NODE_VALVE_SOLUTION_FILL_GPIO 32
#define STORAGE_IRRIGATION_NODE_VALVE_SOLUTION_SUPPLY_GPIO 33
#define STORAGE_IRRIGATION_NODE_VALVE_IRRIGATION_GPIO 14
#define STORAGE_IRRIGATION_NODE_PUMP_FAIL_SAFE_NC 0
#define STORAGE_IRRIGATION_NODE_PUMP_MAX_DURATION_MS 30000U
#define STORAGE_IRRIGATION_NODE_PUMP_MIN_OFF_MS 5000U
#define STORAGE_IRRIGATION_NODE_PUMP_ML_PER_SECOND 2.0f

#define STORAGE_IRRIGATION_NODE_LEVEL_CLEAN_MIN_GPIO 16
#define STORAGE_IRRIGATION_NODE_LEVEL_CLEAN_MAX_GPIO 17
#define STORAGE_IRRIGATION_NODE_LEVEL_SOLUTION_MIN_GPIO 18
#define STORAGE_IRRIGATION_NODE_LEVEL_SOLUTION_MAX_GPIO 19
#define STORAGE_IRRIGATION_NODE_LEVEL_SWITCH_ACTIVE_LOW 1
#define STORAGE_IRRIGATION_NODE_LEVEL_SWITCH_SCAN_INTERVAL_MS 200U
#define STORAGE_IRRIGATION_NODE_LEVEL_SWITCH_POLL_INTERVAL_MS 5000U
#define STORAGE_IRRIGATION_NODE_LEVEL_SWITCH_DEBOUNCE_MS 80U

#define STORAGE_IRRIGATION_NODE_OLED_I2C_ADDRESS 0x3C
#define STORAGE_IRRIGATION_NODE_OLED_UPDATE_INTERVAL_MS 1500

#define STORAGE_IRRIGATION_NODE_SETUP_AP_PASSWORD "hydro2025"

#define STORAGE_IRRIGATION_NODE_FACTORY_RESET_GPIO GPIO_NUM_0
#define STORAGE_IRRIGATION_NODE_FACTORY_RESET_ACTIVE_LOW 1
#define STORAGE_IRRIGATION_NODE_FACTORY_RESET_HOLD_MS 10000U
#define STORAGE_IRRIGATION_NODE_FACTORY_RESET_POLL_INTERVAL 50U

#define STORAGE_IRRIGATION_NODE_CMD_QUEUE_MAX 8
#define STORAGE_IRRIGATION_NODE_DONE_QUEUE_MAX 8
#define STORAGE_IRRIGATION_NODE_CMD_ID_LEN 64
#define STORAGE_IRRIGATION_NODE_IRR_STATE_MAX_AGE_SEC 30

#define STORAGE_IRRIGATION_NODE_SENSOR_SCAN_TASK_STACK_WORDS 4096
#define STORAGE_IRRIGATION_NODE_CURRENT_POLL_TASK_STACK_WORDS 6144
#define STORAGE_IRRIGATION_NODE_PUMP_HEALTH_TASK_STACK_WORDS 8192
#define STORAGE_IRRIGATION_NODE_STATUS_TASK_STACK_WORDS 4096

typedef struct {
    const char *name;
    const char *metric;
    const char *unit;
    int gpio;
    bool active_low;
    uint32_t poll_interval_ms;
    int precision;
} storage_irrigation_node_sensor_channel_t;

typedef struct {
    const char *name;
    int gpio;
    bool fail_safe_nc;
    uint32_t max_duration_ms;
    uint32_t min_off_ms;
    float ml_per_second;
} storage_irrigation_node_actuator_channel_t;

extern const storage_irrigation_node_sensor_channel_t STORAGE_IRRIGATION_NODE_SENSOR_CHANNELS[];
extern const size_t STORAGE_IRRIGATION_NODE_SENSOR_CHANNELS_COUNT;

extern const storage_irrigation_node_actuator_channel_t STORAGE_IRRIGATION_NODE_ACTUATOR_CHANNELS[];
extern const size_t STORAGE_IRRIGATION_NODE_ACTUATOR_CHANNELS_COUNT;

cJSON *storage_irrigation_node_build_config_channels(void);

#ifdef __cplusplus
}
#endif

#endif // STORAGE_IRRIGATION_NODE_CONFIG_H
