<?php

namespace App\Console\Commands;

use App\Models\Greenhouse;
use App\Models\Zone;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class E2EAuthBootstrap extends Command
{
    protected $signature = 'e2e:auth-bootstrap {--email=e2e@test.local} {--role=admin} {--with-zone : Создать тестовую теплицу и зону для E2E}';
    
    protected $description = 'Создает пользователя и токен для E2E тестов';

    public function handle(): int
    {
        $email = $this->option('email');
        $role = $this->option('role');

        // Создаем или получаем пользователя
        $user = User::firstOrCreate(
            ['email' => $email],
            [
                'name' => 'E2E Test User',
                'password' => Hash::make('e2e-test-password'),
                'role' => $role,
                'email_verified_at' => now(),
            ]
        );

        // Обновляем роль, если пользователь уже существовал
        if ($user->role !== $role) {
            $user->role = $role;
            $user->save();
            $this->info("Обновлена роль пользователя: {$role}");
        }

        if ((bool) $this->option('with-zone')) {
            $this->bootstrapZone();
        }

        // Удаляем старые токены для этого пользователя (опционально, для чистоты)
        // $user->tokens()->delete();

        // Создаем новый токен
        $token = $user->createToken('e2e-test-token')->plainTextToken;

        // Выводим токен в stdout (без дополнительных сообщений для удобства парсинга)
        // В non-verbose режиме выводим только токен
        if ($this->getOutput()->isVerbose()) {
            $this->info("E2E User: {$email} | Role: {$role}");
            $this->info("Token:");
            $this->line($token);
        } else {
            // В non-verbose режиме выводим только токен
            $this->line($token);
        }

        return 0;
    }

    private function bootstrapZone(): void
    {
        $greenhouse = Greenhouse::query()->firstOrCreate(
            ['uid' => 'e2e-gh-main'],
            [
                'name' => 'E2E Greenhouse',
                'timezone' => 'UTC',
                'type' => 'greenhouse',
                'description' => 'Autogenerated fixture for Playwright E2E tests',
                'provisioning_token' => 'gh_'.Str::random(32),
            ]
        );

        if (! is_string($greenhouse->provisioning_token) || $greenhouse->provisioning_token === '') {
            $greenhouse->provisioning_token = 'gh_'.Str::random(32);
            $greenhouse->save();
        }

        $zone = Zone::query()->firstOrCreate(
            ['uid' => 'e2e-zone-main'],
            [
                'greenhouse_id' => $greenhouse->id,
                'name' => 'E2E Zone',
                'description' => 'Autogenerated fixture for Playwright E2E tests',
                'status' => 'online',
            ]
        );

        if ($zone->greenhouse_id !== $greenhouse->id) {
            $zone->greenhouse_id = $greenhouse->id;
            $zone->save();
        }

        if ($this->getOutput()->isVerbose()) {
            $this->info('E2E zone fixture ready');
            $this->line('Greenhouse UID: '.$greenhouse->uid.' | Zone UID: '.$zone->uid);
        }
    }
}
