[program:scheduler]
directory=/app
command=/usr/local/bin/php /app/artisan schedule:work --no-interaction
process_name=%(program_name)s
autostart=true
autorestart=true
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/supervisor/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
user=application
priority=998
