export const ZONE_AUTOMATION_FIELD_HELP: Record<string, string> = {
  'device.irrigation': 'Основная нода полива зоны. Через неё runtime ожидает каналы запуска полива и refill/flow-команды для водного узла.',
  'device.ph_correction': 'Нода pH-коррекции. Должна содержать pH sensor и/или dosing channels для кислотной или щелочной коррекции.',
  'device.ec_correction': 'Нода EC-коррекции. Используется для EC sensor и дозирующих насосов удобрений в контуре correction runtime.',
  'device.light': 'Нода освещения, к которой будут привязаны команды досветки и ручного lighting override.',
  'device.soil_moisture_sensor': 'Источник телеметрии влажности субстрата (SOIL_MOISTURE). Нужен для стратегии smart_soil_v1 (умный полив).',
  'device.co2_sensor': 'Источник телеметрии CO2 для zonal climate. От этой ноды зависит измерение ppm внутри зоны.',
  'device.co2_actuator': 'Исполнитель подачи CO2. Нужен, если zonal climate должен управлять инжекцией CO2 в этой зоне.',
  'device.root_vent_actuator': 'Исполнитель прикорневой вентиляции или локального airflow для zonal climate зоны.',
  'water.systemType': 'Базовая гидравлическая схема зоны. От system type зависят допустимые targets, tank layout и runtime command plans.',
  'water.tanksCount': 'Количество баков в контуре. 2 бака включают чистую воду и раствор, 3 бака добавляют отдельный дренажный контур.',
  'water.enableDrainControl': 'Включает контроль процента дренажа. Имеет смысл только для 3-баковой схемы с отдельным drain контуром.',
  'water.drainTargetPercent': 'Целевой процент дренажа относительно подачи. Используется как ориентир для режима с drain control.',
  'water.valveSwitching': 'Разрешает relay-командам переключать клапаны между фазами clean fill, solution fill и recirculation.',
  'water.intervalMinutes': 'Период между штатными поливами. Чем меньше интервал, тем чаще scheduler будет инициировать irrigation workflow.',
  'water.durationSeconds': 'Длительность одного поливочного окна. Это прямое время работы исполнительного контура полива.',
  'water.irrigationBatchL': 'Целевой объём одной порции полива. Используется как агрономический ориентир при настройке цикла.',
  'water.fillTemperatureC': 'Желаемая температура воды на стадии заполнения бака. Нужна как target для приготовления раствора.',
  'water.cleanTankFillL': 'Рабочий объём чистого бака, который runtime стремится набрать перед приготовлением раствора.',
  'water.nutrientTankTargetL': 'Целевой объём бака раствора после подготовки nutrient mix.',
  'water.fillWindowStart': 'Начало разрешённого окна, в которое системе можно запускать набор воды.',
  'water.fillWindowEnd': 'Конец разрешённого окна набора воды. Вне окна runtime не должен инициировать fill workflow.',
  'water.diagnosticsEnabled': 'Разрешает автоматические diagnostic/workflow проверки водного контура перед стартом или по расписанию.',
  'water.diagnosticsIntervalMinutes': 'Как часто запускать diagnostic workflow, если он разрешён для зоны.',
  'water.diagnosticsWorkflow': 'Какой режим diagnostic workflow использовать: при старте, на старте цикла или как отдельную диагностику.',
  'water.cleanTankFullThreshold': 'Порог заполнения чистого бака в долях от 0 до 1, после которого бак считается полным.',
  'water.refillDurationSeconds': 'Штатная длительность одной refill-команды, если требуется дозаполнение чистого бака.',
  'water.refillTimeoutSeconds': 'Максимальное время ожидания завершения refill workflow до признания таймаута.',
  'water.refillRequiredNodeTypes': 'CSV-список типов нод, которые обязаны быть доступны для refill workflow.',
  'water.refillPreferredChannel': 'Предпочтительный channel/alias, который runtime будет использовать для refill-команды.',
  'water.startupCleanFillTimeoutSeconds': 'Fail-closed таймаут на набор чистой воды при startup workflow.',
  'water.startupSolutionFillTimeoutSeconds': 'Fail-closed таймаут на набор раствора при startup workflow.',
  'water.startupPrepareRecirculationTimeoutSeconds': 'Максимальное время ожидания стадии prepare recirculation до аварийного завершения.',
  'water.startupCleanFillRetryCycles': 'Сколько раз startup workflow может повторить clean fill перед отказом.',
  'water.cleanFillMinCheckDelayMs': 'Через сколько миллисекунд после открытия valve_clean_fill нода проверяет level_clean_min и fail-closed останавливает набор, если источник пуст.',
  'water.solutionFillCleanMinCheckDelayMs': 'Через сколько миллисекунд после старта solution_fill нода проверяет level_clean_min и fail-closed останавливает набор при отсутствии clean source.',
  'water.solutionFillSolutionMinCheckDelayMs': 'Через сколько миллисекунд после старта solution_fill выполняется leak-check по level_solution_min.',
  'water.recirculationStopOnSolutionMin': 'Fail-closed guard: prepare recirculation должен останавливаться при lower solution level.',
  'water.estopDebounceMs': 'Debounce физической кнопки аварийной остановки. Пока кнопка нажата, node принудительно держит все актуаторы OFF.',
  'water.irrigationDecisionStrategy': 'Decision-controller штатного полива: task принудительно выполняет запуск по плану, smart_soil_v1 сначала оценивает soil moisture и качество телеметрии.',
  'water.irrigationDecisionLookbackSeconds': 'Глубина окна истории телеметрии, из которого decision-controller берёт soil moisture samples.',
  'water.irrigationDecisionMinSamples': 'Минимум samples в lookback-окне, без которого smart_soil_v1 должен деградировать или skip-нуть запуск.',
  'water.irrigationDecisionStaleAfterSeconds': 'Порог stale telemetry: если последние данные старше этого окна, decision-controller не должен считать их надёжными.',
  'water.irrigationDecisionHysteresisPct': 'Гистерезис вокруг target moisture, который уменьшает лишние запуски полива на шумных данных.',
  'water.irrigationDecisionSpreadAlertThresholdPct': 'Порог разброса датчиков влажности, после которого smart_soil_v1 должен считать зону неоднородной и поднять degraded signal.',
  'water.irrigationRecoveryMaxContinueAttempts': 'Максимум продолжений recovery-окна после полива, если targets ещё не достигнуты.',
  'water.irrigationRecoveryTimeoutSeconds': 'Общий таймаут recovery-фазы после полива.',
  'water.irrigationAutoReplayAfterSetup': 'Разрешает AE3 автоматически повторить normal irrigation после setup/recovery, если initial launch был отложен или оборван safety-path.',
  'water.irrigationMaxSetupReplays': 'Сколько раз runtime может автоматически переиграть irrigation после setup/recovery без нового operator trigger.',
  'water.stopOnSolutionMin': 'Fail-closed guard: normal irrigation должен останавливаться при low-solution signal, а не продолжать workflow вслепую.',
  'water.manualIrrigationSeconds': 'Стандартная длительность ручного полива из UI, если оператор запускает irrigation вручную.',
  'water.solutionChangeEnabled': 'Включает плановую замену раствора по расписанию, отдельную от обычного поливочного цикла.',
  'water.solutionChangeIntervalMinutes': 'Интервал между плановыми заменами раствора, если этот режим включён.',
  'water.solutionChangeDurationSeconds': 'Сколько длится одно окно плановой смены раствора.',
  'water.targetPh': 'Readonly поле. Канонический target pH берётся только из активной фазы рецепта и не сохраняется в zone logic profile.',
  'water.targetEc': 'Readonly поле. Канонический target EC берётся только из активной фазы рецепта и не сохраняется в zone logic profile.',
  'water.correctionDuringIrrigation': 'Разрешает correction runtime работать прямо во время irrigation path, а не только до него.',
  'water.correctionMaxEcCorrectionAttempts': 'Максимум dosing-попыток EC-коррекции в одном correction window.',
  'water.correctionMaxPhCorrectionAttempts': 'Максимум dosing-попыток pH-коррекции в одном correction window.',
  'water.correctionPrepareRecirculationMaxAttempts': 'Сколько recirculation-окон runtime может открыть при неуспешной коррекции.',
  'water.correctionPrepareRecirculationMaxCorrectionAttempts': 'Жёсткий лимит внутренних correction-шагов до fail-closed остановки.',
  'water.correctionStabilizationSec': 'Дополнительное время ожидания после дозы, чтобы измерения стабилизировались перед следующим решением.',
  'lighting.enabled': 'Включает подсистему досветки для зоны и делает lighting configuration частью профиля автоматики.',
  'lighting.luxDay': 'Целевая освещённость днём, которой runtime должен придерживаться в дневном окне.',
  'lighting.luxNight': 'Целевая освещённость ночью. Обычно 0, если ночью досветка не нужна.',
  'lighting.hoursOn': 'Суммарная желаемая длительность света в сутки.',
  'lighting.scheduleStart': 'Время старта дневного lighting window.',
  'lighting.scheduleEnd': 'Время завершения lighting window.',
  'lighting.intervalMinutes': 'Частота пересчёта и обновления lighting automation в минутах.',
  'lighting.manualIntensity': 'Интенсивность в процентах для ручного режима досветки.',
  'lighting.manualDurationHours': 'Длительность ручного lighting override в часах.',
  'zoneClimate.enabled': 'Включает подсистему zonal climate в zone.logic_profile (флаг и capabilities). Узлы CO₂ и прикорневой вентиляции привязываются в мастере запуска; не смешивать с макроклиматом теплицы (greenhouse.logic_profile).',
}

export function zoneAutomationFieldHelp(key: string): string {
  return ZONE_AUTOMATION_FIELD_HELP[key] ?? 'Параметр профиля автоматики зоны.'
}
